[package]
name = "demucs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
demucs-core = { path = "../demucs-core" }
wasm-bindgen = "0.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
